import { describe,expect,it } from 'vitest'
import { createBs12MintWaferDemoState,createBs12EntranceDemoState,createBs12WorkshopDemoState,createBs12SpotlightDemoState,createCardCheckDemoState,createCardNegativeDemoState,parseTestStateConfig } from './demo'
import { assertBs12PhysicalFixture } from './bs12-physical-fixtures.test-helpers'

describe('BS12-029 physical resources',()=>{it.each(["four","three","five","arena-only","yellow-only","non-arena","high-level","opponent-break","trash-arena","support-arena","battle-arena","no-energy","wrong-energy","rested-energy","disabled","used","main","after-battle","one-energy","mixed-energy","one-rested","short-deck","event-only"] as const)('%s preserves all printed attributes and legal equipment recipients',scenario=>assertBs12PhysicalFixture(createBs12EntranceDemoState(scenario)))})

describe('BS12-030 physical resources',()=>{it.each(["positive","faint","green-arena","hand-break","removed-break","old-break","previous-turn","non-arena","opponent-break","trash-arena","no-event","no-energy","wrong-energy","rested-energy","one-energy","rested-source","opponent-turn","wrong-phase","non-arena-target","red-target","rested-target","equipment","support-only","no-target","replace","placed","refresh"] as const)('%s preserves all printed attributes and legal equipment recipients',scenario=>assertBs12PhysicalFixture(createBs12WorkshopDemoState(scenario)))})

describe('BS12-031 physical resources',()=>{it.each(["positive","two-costs","no-cost","red-arena","yellow-non-arena","equipment-only","support-only","rested-cost","no-energy","one-energy","wrong-energy","mixed-energy","rested-energy","opponent-turn","outside-main","break-nine","single-cookie","equipped-cost","opponent-faints","no-target","short-deck"] as const)('%s preserves all printed attributes and legal equipment recipients',scenario=>assertBs12PhysicalFixture(createBs12SpotlightDemoState(scenario)))})

it('022 equipment is on a physical nonArena Shining Glitter Cookie',()=>{const state=createBs12MintWaferDemoState('equipment');assertBs12PhysicalFixture(state);const host=state.players['player-one'].battleArea.find(entry=>entry.equippedCards?.some(card=>card.id==='BS12-007'))!;expect(host.card).toMatchObject({id:'BS4-095',name:'Shining Glitter Cookie'});expect(host.card.keywords ?? []).not.toContain('ARENA')})

it.each(['BS12-029','BS12-030','BS12-031'] as const)('%s aliases load mechanism resources',number=>{const scenarios=number==='BS12-029'?['four','one-energy']:number==='BS12-030'?['positive','no-event']:['positive','no-cost'];for(const [index,prefix] of ['card','card-negative'].entries()){expect(parseTestStateConfig(`?test-state=${prefix}:${number}`,'localhost')).toEqual({kind:number.toLowerCase(),scenario:scenarios[index]});expect(parseTestStateConfig(`?test-state=${prefix}:${number}`,'example.com')).toBeNull()}assertBs12PhysicalFixture(createCardCheckDemoState(number));assertBs12PhysicalFixture(createCardNegativeDemoState(number))})

it('029 disabled has real printed equipment and LV8 blocking',()=>{const state=createBs12EntranceDemoState('disabled');const attacker=state.players['player-two'].battleArea[0];expect(attacker.card.id).toBe('BS8-009');expect(attacker.equippedCards?.map(card=>card.id)).toEqual(['BS8-021']);expect(state.pendingBattle).toMatchObject({trapsDisabled:true,remainingDamage:3})})

it('029 used control actually paid YY for a first029 and retains the second029',()=>{const state=createBs12EntranceDemoState('used');expect(state.players['player-one'].discardPile.map(card=>card.id)).toContain('BS12-029');expect(state.players['player-one'].hand.map(card=>card.instanceId)).toEqual(['bs12-029-trap']);expect(state.players['player-one'].supportArea.map(entry=>entry.rested)).toEqual([true,true]);expect(state.pendingBattle).toMatchObject({trapUsed:true,stage:'damage'})})
