import {expect,it} from 'vitest'
import * as demos from './demo'
import {assertBs12PhysicalFixture} from './bs12-physical-fixtures.test-helpers'
import {applyGameCommand} from './commands'


it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint-four","faint-three","faint-five","mixed-break","wrong-zones","no-target","other-color","non-arena-target","no-hand-faint","direct-attack","last-hp-flip","lv10-defeat","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","twice","second-response"]as const)('BS12-090 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12MilkyWayDemoState('BS12-090',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint-four","faint-three","faint-five","mixed-break","wrong-zones","no-target","other-color","non-arena-target","no-hand-faint","direct-attack","last-hp-flip","lv10-defeat","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","twice","second-response"]as const)('BS12-090@1 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12MilkyWayDemoState('BS12-090@1',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint","direct-attack","no-hand-faint","old-target","zero-target","same-name-only","other-color","non-arena-target","no-blocker-target","short-deck","empty-deck","exact-deck","unpayable","refresh-defeat","last-hp-flip","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","second-response"]as const)('BS12-091 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12CaramelArrowDemoState('BS12-091',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint","direct-attack","no-hand-faint","old-target","zero-target","same-name-only","other-color","non-arena-target","no-blocker-target","short-deck","empty-deck","exact-deck","unpayable","refresh-defeat","last-hp-flip","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","second-response"]as const)('BS12-091@1 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12CaramelArrowDemoState('BS12-091@1',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["attack","two-blockers","one-blocker","no-blocker","wrong-zones","ordinary-faint","damage-faint","last-hp-flip","refresh","refresh-defeat","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","response","item-cost","stage-cost","trap-cost","no-hand","wrong-hand-color","non-arena-hand","split-hand","rested-blocker","second-response"]as const)('BS12-093 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12RockstarDemoState('BS12-093',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["attack","two-blockers","one-blocker","no-blocker","wrong-zones","ordinary-faint","damage-faint","last-hp-flip","refresh","refresh-defeat","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","response","item-cost","stage-cost","trap-cost","no-hand","wrong-hand-color","non-arena-hand","split-hand","rested-blocker","second-response"]as const)('BS12-093@1 partialdraft %s has exact physicalrecords/copies andknowninitialHP',scenario=>{const state=demos.createBs12RockstarDemoState('BS12-093@1',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp);if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(['BS12-090','BS12-090@1']as const)('%s partialdraft actualprintednormaldamage causesfaint fromfresh4HP',number=>{const before=demos.createBs12MilkyWayDemoState(number,'faint-four');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(4);expect(before.players['player-two'].battleArea[0].card.id).toBe('BS12-019');expect(before.commandLog?.map(c=>c.commandKind)).toEqual(['declare-attack']);let state=applyGameCommand(before,{kind:'play-blocker',playerId:'player-one',sourceInstanceId:'bs12-090-source',paymentIds:[],discardHandIds:['bs12-090-cost']});for(let hit=0;hit<4;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.players['player-one'].breakArea.some(c=>c.instanceId==='bs12-090-source')).toBe(true);expect(state.pendingFaintEffects).toHaveLength(1);expect(state.pendingFaintEffects?.[0].sourceInstanceId).toBe('bs12-090-source');expect(state.players['player-one'].supportArea).toEqual(before.players['player-one'].supportArea)})

it.each(['BS12-090','BS12-090@1']as const)('%s partialdraft lastHPFLIP follows4realHP andrescues withoutleftoverdamage',number=>{const before=demos.createBs12MilkyWayDemoState(number,'last-hp-flip');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(4);let state=applyGameCommand(before,{kind:'skip-trap',playerId:'player-one'});for(let hit=0;hit<4;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.pendingBattle?.revealedHpCard?.id).toBe('BS12-002');expect(state.players['player-one'].battleArea[0].hpCards).toHaveLength(0);expect(state.pendingFaintEffects).toBeFalsy();state=applyGameCommand(state,{kind:'resolve-flip',playerId:'player-one',activate:true,discardHandIds:['bs12-090-cost'],targetIds:['bs12-090-source']});assertBs12PhysicalFixture(state);expect(state.players['player-one'].battleArea[0].hpCards).toHaveLength(1);expect(state.pendingFaintEffects).toBeFalsy();expect(state.players['player-one'].breakArea).toEqual(before.players['player-one'].breakArea)})

it.each(['BS12-091','BS12-091@1']as const)('%s partialdraft actualprintednormaldamage causesfaint fromfresh2HP',number=>{const before=demos.createBs12CaramelArrowDemoState(number,'faint');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(2);expect(before.players['player-two'].battleArea[0].card.id).toBe('BS12-091');expect(before.commandLog?.map(c=>c.commandKind)).toEqual(['declare-attack']);let state=applyGameCommand(before,{kind:'play-blocker',playerId:'player-one',sourceInstanceId:'bs12-091-source',paymentIds:[],discardHandIds:['bs12-091-cost']});for(let hit=0;hit<2;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.players['player-one'].breakArea.some(c=>c.instanceId==='bs12-091-source')).toBe(true);expect(state.pendingFaintEffects).toHaveLength(1);expect(state.pendingFaintEffects?.[0].sourceInstanceId).toBe('bs12-091-source');expect(state.players['player-one'].supportArea).toEqual(before.players['player-one'].supportArea)})

it.each(['BS12-091','BS12-091@1']as const)('%s partialdraft lastHPFLIP follows2realHP andrescues withoutleftoverdamage',number=>{const before=demos.createBs12CaramelArrowDemoState(number,'last-hp-flip');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(2);let state=applyGameCommand(before,{kind:'skip-trap',playerId:'player-one'});for(let hit=0;hit<2;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.pendingBattle?.revealedHpCard?.id).toBe('BS12-002');expect(state.players['player-one'].battleArea[0].hpCards).toHaveLength(0);expect(state.pendingFaintEffects).toBeFalsy();state=applyGameCommand(state,{kind:'resolve-flip',playerId:'player-one',activate:true,discardHandIds:['bs12-091-cost'],targetIds:['bs12-091-source']});assertBs12PhysicalFixture(state);expect(state.players['player-one'].battleArea[0].hpCards).toHaveLength(1);expect(state.pendingFaintEffects).toBeFalsy();expect(state.players['player-one'].breakArea).toEqual(before.players['player-one'].breakArea)})

it.each(['BS12-090','BS12-090@1']as const)('%s partialdraft publicnormalentry getsprinted4HP fromphysicaldeck',number=>{const before=demos.createBs12MilkyWayDemoState(number,'deploy');assertBs12PhysicalFixture(before);const after=applyGameCommand(before,{kind:'deploy-cookie',playerId:'player-one',instanceId:'bs12-090-source'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].battleArea.find(c=>c.card.instanceId==='bs12-090-source')?.hpCards).toEqual(before.players['player-one'].deck.slice(0,4));expect(after.commandLog?.at(-1)?.commandKind).toBe('deploy-cookie')})

it.each(['BS12-091','BS12-091@1']as const)('%s partialdraft publicnormalentry getsprinted2HP fromphysicaldeck',number=>{const before=demos.createBs12CaramelArrowDemoState(number,'deploy');assertBs12PhysicalFixture(before);const after=applyGameCommand(before,{kind:'deploy-cookie',playerId:'player-one',instanceId:'bs12-091-source'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].battleArea.find(c=>c.card.instanceId==='bs12-091-source')?.hpCards).toEqual(before.players['player-one'].deck.slice(0,2));expect(after.commandLog?.at(-1)?.commandKind).toBe('deploy-cookie')})

it.each(['BS12-093','BS12-093@1']as const)('%s partialdraft publicnormalentry getsprinted4HP fromphysicaldeck',number=>{const before=demos.createBs12RockstarDemoState(number,'deploy');assertBs12PhysicalFixture(before);const after=applyGameCommand(before,{kind:'deploy-cookie',playerId:'player-one',instanceId:'bs12-093-source'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].battleArea.find(c=>c.card.instanceId==='bs12-093-source')?.hpCards).toEqual(before.players['player-one'].deck.slice(0,4));expect(after.commandLog?.at(-1)?.commandKind).toBe('deploy-cookie')})



it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","direct-attack","unrelated","faints","lv2","lv5","support-source","trash-source","break-source","hand-source","last-hp-flip","zero-damage","redirect-away","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","attacker-lv3","attacker-lv2","attacker-lv5","attacker-faints","attacker-unrelated","twice","second-battle","second-response","all-opponents","attacker-all-opponents"]as const)('BS12-089 partialdraft %s uses physicalrecords anddocumentedHPparents',scenario=>{const state=demos.createBs12WerewolfDemoState('BS12-089',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea){if(cookie.card.id==='BS11-116'){expect(cookie.hpCards).toHaveLength(8);expect(state.commandLog?.some(c=>c.commandKind==='play-extra-deck-cookie')).toBe(true)}else expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)}if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","direct-attack","unrelated","faints","lv2","lv5","support-source","trash-source","break-source","hand-source","last-hp-flip","zero-damage","redirect-away","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main","attacker-lv3","attacker-lv2","attacker-lv5","attacker-faints","attacker-unrelated","twice","second-battle","second-response","all-opponents","attacker-all-opponents"]as const)('BS12-089@1 partialdraft %s uses physicalrecords anddocumentedHPparents',scenario=>{const state=demos.createBs12WerewolfDemoState('BS12-089@1',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea){if(cookie.card.id==='BS11-116'){expect(cookie.hpCards).toHaveLength(8);expect(state.commandLog?.some(c=>c.commandKind==='play-extra-deck-cookie')).toBe(true)}else expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)}if(scenario==='outside-main')expect(state.phase).toBe('support')})

it.each(['BS12-089','BS12-089@1']as const)('%s original5HP getsrealDJPP2beforecurrentLV3normal3faint',number=>{const before=demos.createBs12WerewolfDemoState(number,'faints');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].card.hp).toBe(5);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(3);expect(before.players['player-two'].battleArea[1].card.id).toBe('BS12-082');expect(before.players['player-two'].battleArea[1].rested).toBe(true);expect(before.commandLog?.map(c=>c.commandKind)).toEqual(['declare-attack','skip-trap','resolve-next-damage','resolve-next-damage','declare-attack']);let state=applyGameCommand(before,{kind:'skip-trap',playerId:'player-one'});for(let hit=0;hit<3;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.players['player-one'].breakArea.some(c=>c.instanceId==='bs12-089-source')).toBe(true)})

it.each(['BS12-089','BS12-089@1']as const)('%s lastHPFLIP followsreal5HPminusDJ2thenLV3normal3',number=>{const before=demos.createBs12WerewolfDemoState(number,'last-hp-flip');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(3);let state=applyGameCommand(before,{kind:'skip-trap',playerId:'player-one'});for(let hit=0;hit<3;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(state);expect(state.pendingBattle?.revealedHpCard?.id).toBe('BS12-002');state=applyGameCommand(state,{kind:'resolve-flip',playerId:'player-one',activate:true,discardHandIds:['bs12-089-cost'],targetIds:['bs12-089-source']});assertBs12PhysicalFixture(state);expect(state.players['player-one'].battleArea[0].hpCards).toHaveLength(1);expect(state.players['player-one'].breakArea).toEqual([])})

it.each(['BS12-089','BS12-089@1']as const)('%s LV5reference actualAwaken adds2toindependentlyprinted6HP',number=>{const state=demos.createBs12WerewolfDemoState(number,'lv5');assertBs12PhysicalFixture(state);const awakened=state.players['player-two'].battleArea[0];expect(awakened.card.id).toBe('BS11-116');expect(awakened.hpCards).toHaveLength(8);expect(awakened.hpCards.filter(c=>c.instanceId.startsWith('bs12-089-awaken-underlay-hp-'))).toHaveLength(6);expect(awakened.awakenedUnderlay?.map(c=>c.id)).toEqual(['BS11-115']);expect(state.players['player-two'].deck).toHaveLength(10);expect(state.commandLog?.map(c=>c.commandKind)).toEqual(['play-extra-deck-cookie','declare-attack'])})

const own='player-one',enemy='player-two',source='bs12-092-source'
for(const number of ['BS12-092','BS12-092@1'] as const){
 it.each(demos.BS12_BLACK_LEMONADE_SCENARIOS)('%s '+number+' physical identity and documented initial HP',scenario=>{
  const state=demos.createBs12BlackLemonadeDemoState(number,scenario)
  assertBs12PhysicalFixture(state)
  const cookie=state.players[own].battleArea.find(c=>c.card.instanceId===source)
  if(cookie){expect(cookie.card.hp).toBe(5);expect(cookie.hpCards).toHaveLength(scenario==='source-faint'?4:5)}
  if(scenario==='outside-main')expect(state.phase).toBe('support')
 })
 it(number+' EXTRA entry pays printed3HP Gnome without faint and installs5HP',()=>{
  const before=demos.createBs12BlackLemonadeDemoState(number,'extra-full')
  assertBs12PhysicalFixture(before)
  expect(before.players[own].battleArea[0].card.id).toBe('BS12-075')
  expect(before.players[own].battleArea[0].hpCards).toHaveLength(3)
  const pending=applyGameCommand(before,{kind:'play-extra-deck-cookie',playerId:own,instanceId:source})
  const after=applyGameCommand(pending,{kind:'resolve-optional-cost-attack',playerId:own,action:'pay',targetIds:['bs12-092-cost'],paymentIds:[],discardCardIds:[]})
  assertBs12PhysicalFixture(after)
  expect(after.players[own].battleArea.map(c=>c.card.instanceId)).toEqual(['bs12-092-other',source])
  expect(after.players[own].battleArea[0].hpCards).toHaveLength(2)
  expect(after.players[own].battleArea[1].hpCards).toEqual(before.players[own].deck.slice(0,5))
  expect(after.players[own].discardPile).toEqual([before.players[own].battleArea[0].card,...before.players[own].battleArea[0].hpCards])
  expect(after.players[own].breakArea).toEqual(before.players[own].breakArea)
  expect(after.cookiesFaintedThisTurn?.[own]??0).toBe(0)
  expect(after.pendingFaintEffects).toBeFalsy()
 })
 it(number+' actualPeachR1 faints nonArenaPink1 and queues living listener',()=>{
  const before=demos.createBs12BlackLemonadeDemoState(number,'friendly-faint')
  assertBs12PhysicalFixture(before)
  expect(before.players[own].battleArea[1].card.id).toBe('BS6-017')
  expect(before.players[own].battleArea[1].hpCards).toHaveLength(1)
  expect(before.players[enemy].battleArea[0].card.id).toBe('BS12-003')
  expect(before.commandLog?.map(c=>c.commandKind)).toEqual(['declare-attack'])
  let state=applyGameCommand(before,{kind:'skip-trap',playerId:own})
  state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:own})
  assertBs12PhysicalFixture(state)
  expect(state.players[own].breakArea.some(c=>c.instanceId==='bs12-092-ally')).toBe(true)
  expect(state.players[own].battleArea[0].hpCards).toHaveLength(5)
  expect(state.pendingFaintEffects?.[0].sourceInstanceId).toBe(source)
 })
 it(number+' source5HP receives actualPeach1 thenMuscle4 and leaves no living listener',()=>{
  const before=demos.createBs12BlackLemonadeDemoState(number,'source-faint')
  assertBs12PhysicalFixture(before)
  expect(before.players[own].battleArea[0].card.hp).toBe(5)
  expect(before.players[own].battleArea[0].hpCards).toHaveLength(4)
  expect(before.commandLog?.map(c=>c.commandKind)).toEqual(['declare-attack','skip-trap','resolve-next-damage','declare-attack'])
  expect(before.players[enemy].battleArea.map(c=>c.card.id)).toEqual(['BS12-019','BS12-003'])
  let state=applyGameCommand(before,{kind:'skip-trap',playerId:own})
  for(let hit=0;hit<4;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:own})
  assertBs12PhysicalFixture(state)
  expect(state.players[own].breakArea.some(c=>c.instanceId===source)).toBe(true)
  expect(state.pendingFaintEffects?.length??0).toBe(0)
 })
 it(number+' actualPeach1 reveals lastHP FLIP and rescue prevents faint trigger',()=>{
  const before=demos.createBs12BlackLemonadeDemoState(number,'last-hp-flip')
  assertBs12PhysicalFixture(before)
  expect(before.players[own].battleArea[1].card.id).toBe('BS12-080')
  let state=applyGameCommand(before,{kind:'skip-trap',playerId:own})
  state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:own})
  expect(state.pendingBattle?.revealedHpCard?.id).toBe('BS12-002')
  expect(state.pendingFaintEffects).toBeFalsy()
  state=applyGameCommand(state,{kind:'resolve-flip',playerId:own,activate:true,discardHandIds:['bs12-092-flip-cost'],targetIds:['bs12-092-ally']})
  assertBs12PhysicalFixture(state)
  expect(state.players[own].battleArea[1].hpCards).toHaveLength(1)
  expect(state.players[own].breakArea).toEqual([])
  expect(state.pendingFaintEffects).toBeFalsy()
 })
 it(number+' ordinaryPPPP4 leaves printedCreamPuff5 with1HP',()=>{
  const before=demos.createBs12BlackLemonadeDemoState(number,'attack')
  assertBs12PhysicalFixture(before)
  expect(before.players[enemy].battleArea[0].card.id).toBe('BS12-064')
  expect(before.players[enemy].battleArea[0].hpCards).toHaveLength(5)
  let state=applyGameCommand(before,{kind:'declare-attack',playerId:own,attackerInstanceId:source,targetInstanceId:'bs12-092-opponent',supportPaymentIds:before.players[own].supportArea.map(s=>s.card.instanceId)})
  state=applyGameCommand(state,{kind:'skip-trap',playerId:enemy})
  for(let hit=0;hit<4;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:enemy})
  assertBs12PhysicalFixture(state)
  expect(state.players[enemy].battleArea[0].hpCards).toHaveLength(1)
  expect(state.pendingBattle?.stage).toBe('attack-effect')
 })
}

it.each(['BS12-089','BS12-089@1']as const)('%s generic routes preserve physical printed effect resources',number=>{expect(demos.parseTestStateConfig('?test-state=card:'+number,'localhost')).toEqual({kind:'bs12-089',cardNumber:number,scenario:'response'});expect(demos.parseTestStateConfig('?test-state=card-negative:'+number,'localhost')).toEqual({kind:'bs12-089',cardNumber:number,scenario:'non-arena'});assertBs12PhysicalFixture(demos.createCardCheckDemoState(number));assertBs12PhysicalFixture(demos.createCardNegativeDemoState(number));expect(demos.parseTestStateConfig('?test-state=card:'+number,'example.com')).toBeNull()})
it.each(['BS12-090','BS12-090@1']as const)('%s generic routes preserve physical printed effect resources',number=>{expect(demos.parseTestStateConfig('?test-state=card:'+number,'localhost')).toEqual({kind:'bs12-090',cardNumber:number,scenario:'faint-four'});expect(demos.parseTestStateConfig('?test-state=card-negative:'+number,'localhost')).toEqual({kind:'bs12-090',cardNumber:number,scenario:'faint-three'});assertBs12PhysicalFixture(demos.createCardCheckDemoState(number));assertBs12PhysicalFixture(demos.createCardNegativeDemoState(number));expect(demos.parseTestStateConfig('?test-state=card:'+number,'example.com')).toBeNull()})
it.each(['BS12-091','BS12-091@1']as const)('%s generic routes preserve physical printed effect resources',number=>{expect(demos.parseTestStateConfig('?test-state=card:'+number,'localhost')).toEqual({kind:'bs12-091',cardNumber:number,scenario:'faint'});expect(demos.parseTestStateConfig('?test-state=card-negative:'+number,'localhost')).toEqual({kind:'bs12-091',cardNumber:number,scenario:'no-blocker-target'});assertBs12PhysicalFixture(demos.createCardCheckDemoState(number));assertBs12PhysicalFixture(demos.createCardNegativeDemoState(number));expect(demos.parseTestStateConfig('?test-state=card:'+number,'example.com')).toBeNull()})
it.each(['BS12-092','BS12-092@1']as const)('%s generic routes preserve physical printed effect resources',number=>{expect(demos.parseTestStateConfig('?test-state=card:'+number,'localhost')).toEqual({kind:'bs12-092',cardNumber:number,scenario:'extra'});expect(demos.parseTestStateConfig('?test-state=card-negative:'+number,'localhost')).toEqual({kind:'bs12-092',cardNumber:number,scenario:'break-two'});assertBs12PhysicalFixture(demos.createCardCheckDemoState(number));assertBs12PhysicalFixture(demos.createCardNegativeDemoState(number));expect(demos.parseTestStateConfig('?test-state=card:'+number,'example.com')).toBeNull()})
it.each(['BS12-093','BS12-093@1']as const)('%s generic routes preserve physical printed effect resources',number=>{expect(demos.parseTestStateConfig('?test-state=card:'+number,'localhost')).toEqual({kind:'bs12-093',cardNumber:number,scenario:'attack'});expect(demos.parseTestStateConfig('?test-state=card-negative:'+number,'localhost')).toEqual({kind:'bs12-093',cardNumber:number,scenario:'one-blocker'});assertBs12PhysicalFixture(demos.createCardCheckDemoState(number));assertBs12PhysicalFixture(demos.createCardNegativeDemoState(number));expect(demos.parseTestStateConfig('?test-state=card:'+number,'example.com')).toBeNull()})
it.each(['BS12-089','BS12-089@1']as const)('%s real normal deployment installs printed5HP',number=>{const before=demos.createBs12WerewolfDemoState(number,'deploy');assertBs12PhysicalFixture(before);const after=applyGameCommand(before,{kind:'deploy-cookie',playerId:'player-one',instanceId:'bs12-089-source'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].battleArea.find(c=>c.card.instanceId==='bs12-089-source')?.hpCards).toEqual(before.players['player-one'].deck.slice(0,5));expect(after.commandLog?.at(-1)?.commandKind).toBe('deploy-cookie')})

it.each(['BS12-093','BS12-093@1']as const)('%s ordinary3then independent1 uses printedCreamPuff5 andKohlrabi1',number=>{const before=demos.createBs12RockstarDemoState(number,'damage-faint');assertBs12PhysicalFixture(before);expect(before.players['player-two'].battleArea.map(c=>c.card.id)).toEqual(['BS12-064','BS12-080']);expect(before.players['player-two'].battleArea.map(c=>c.hpCards.length)).toEqual([5,1]);let state=applyGameCommand(before,{kind:'declare-attack',playerId:'player-one',attackerInstanceId:'bs12-093-source',targetInstanceId:'bs12-093-opponent',supportPaymentIds:before.players['player-one'].supportArea.map(s=>s.card.instanceId)});state=applyGameCommand(state,{kind:'skip-trap',playerId:'player-two'});for(let hit=0;hit<3;hit++)state=applyGameCommand(state,{kind:'resolve-next-damage',playerId:'player-two'});expect(state.players['player-two'].battleArea.map(c=>c.hpCards.length)).toEqual([2,1]);state=applyGameCommand(state,{kind:'resolve-attack-effect',playerId:'player-one',targetIds:[]});state=applyGameCommand(state,{kind:'resolve-optional-cost-attack',playerId:'player-one',action:'pay',trashToDeckIds:['bs12-093-red-blocker','bs12-093-blocker'],targetIds:['bs12-093-opponent-other']});expect(state.pendingBattle).toBeFalsy();assertBs12PhysicalFixture(state);expect(state.players['player-two'].battleArea.map(c=>c.hpCards.length)).toEqual([2]);expect(state.players['player-two'].breakArea.some(c=>c.instanceId==='bs12-093-opponent-other')).toBe(true);expect(state.players['player-one'].deck.slice(-2).map(c=>c.instanceId)).toEqual(['bs12-093-red-blocker','bs12-093-blocker'])})
