import {expect,it} from 'vitest'
import * as demos from './demo'
import {assertBs12PhysicalFixture} from './bs12-physical-fixtures.test-helpers'
import {applyGameCommand} from './commands'

it.each(["positive","five","seven","three-blockers","one-blocker","no-blocker","wrong-energy","rested-energy","no-energy","rested-source","opponent-turn","outside-main","place","replace","one-energy","placement-wrong-energy","placement-rested-energy","placement-no-energy","receiver"]as const)('BS12-084 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12SummerSodaDemoState(scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(["positive","four","six","zero","wrong-zones","wrong-energy","rested-energy","no-energy","opponent-turn","outside-main","short-deck","spare-energy","dj-four","dj-five","dj-no-hand"]as const)('BS12-085 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12RainbowHeadphonesDemoState(scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(["positive","rested-target","non-blocker","no-target","wrong-zones","wrong-energy","rested-energy","no-energy","spare-energy","disabled","used","main","after-battle","next-turn"]as const)('BS12-086 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12TrueRockSpiritDemoState(scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(["nine","eight","ten","mixed","non-arena","opponent-trash","other-zones","wrong-energy","rested-energy","no-energy","one-energy","one-rested","spare-energy","disabled","used","main","after-battle","dj","expired"]as const)('BS12-087 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12UnderstandingDemoState(scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint","only-block-cost","no-faint-cost","faint-red-item","faint-purple-trap","direct-attack","short-deck","empty-deck","refresh-defeat","lv10-defeat","twice","second-response","last-hp-flip","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main"]as const)('BS12-088 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12BlackSapphireDemoState('BS12-088',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(["response","item-cost","stage-cost","trap-cost","rested-source","wrong-color","non-arena","split-cost","no-hand","faint","only-block-cost","no-faint-cost","faint-red-item","faint-purple-trap","direct-attack","short-deck","empty-deck","refresh-defeat","lv10-defeat","twice","second-response","last-hp-flip","attack","deploy","wrong-energy","few-energy","rested-energy","source-rested","opponent-turn","outside-main"]as const)('BS12-088@1 draft %s keeps exact physical cards and documented initialHP',scenario=>{const state=demos.createBs12BlackSapphireDemoState('BS12-088@1',scenario);assertBs12PhysicalFixture(state);for(const player of Object.values(state.players))for(const cookie of player.battleArea)expect(cookie.hpCards.length,cookie.card.name).toBeLessThanOrEqual(cookie.card.hp)})

it.each(['BS12-088','BS12-088@1']as const)('%s faint is caused by printedPPP3 against freshprinted3HP',number=>{
 const before=demos.createBs12BlackSapphireDemoState(number,'faint');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(3);expect(before.players['player-two'].battleArea[0].card.id).toBe('BS12-078');expect(before.players['player-two'].battleArea[0].hpCards).toHaveLength(3);expect(before.commandLog?.map(r=>r.commandKind)).toEqual(['declare-attack']);expect(before.players['player-two'].supportArea.map(s=>s.rested)).toEqual([true,true,true]);
 const blocked=applyGameCommand(before,{kind:'play-blocker',playerId:'player-one',sourceInstanceId:'bs12-088-source',paymentIds:[],discardHandIds:['bs12-088-block-cost']});let after=blocked;for(let hit=0;hit<3;hit++)after=applyGameCommand(after,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].breakArea.some(c=>c.instanceId==='bs12-088-source')).toBe(true);expect(after.pendingFaintEffects).toHaveLength(1);expect(after.pendingFaintEffects?.[0].effect).toEqual({kind:'draw-up-to',max:2});expect(after.players['player-one'].supportArea).toEqual(before.players['player-one'].supportArea)
})

it.each(['BS12-088','BS12-088@1']as const)('%s lastHP printedFLIP can rescue after three actualdamage without leftoverfourthdamage',number=>{
 const before=demos.createBs12BlackSapphireDemoState(number,'last-hp-flip');assertBs12PhysicalFixture(before);expect(before.players['player-one'].battleArea[0].hpCards).toHaveLength(3);const blocked=applyGameCommand(before,{kind:'play-blocker',playerId:'player-one',sourceInstanceId:'bs12-088-source',paymentIds:[],discardHandIds:['bs12-088-block-cost']});let revealed=blocked;for(let hit=0;hit<3;hit++)revealed=applyGameCommand(revealed,{kind:'resolve-next-damage',playerId:'player-one'});assertBs12PhysicalFixture(revealed);expect(revealed.pendingBattle?.revealedHpCard?.id).toBe('BS12-002');expect(revealed.players['player-one'].battleArea[0].hpCards).toHaveLength(0);expect(revealed.pendingFaintEffects).toBeFalsy();const rescued=applyGameCommand(revealed,{kind:'resolve-flip',playerId:'player-one',activate:true,discardHandIds:['bs12-088-faint-cost'],targetIds:['bs12-088-source']});assertBs12PhysicalFixture(rescued);expect(rescued.players['player-one'].battleArea.map(c=>c.hpCards.length)).toEqual([1,4]);expect(rescued.players['player-one'].breakArea).toEqual([]);expect(rescued.pendingFaintEffects).toBeFalsy()
})

it('BS12-084 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','positive'],['card-negative','no-blocker']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-084','localhost')).toEqual({kind:'bs12-084',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-084','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-084'):demos.createCardNegativeDemoState('BS12-084');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12SummerSodaDemoState(scenario))}})

it('BS12-085 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','positive'],['card-negative','four']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-085','localhost')).toEqual({kind:'bs12-085',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-085','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-085'):demos.createCardNegativeDemoState('BS12-085');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12RainbowHeadphonesDemoState(scenario))}})

it('BS12-086 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','positive'],['card-negative','no-target']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-086','localhost')).toEqual({kind:'bs12-086',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-086','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-086'):demos.createCardNegativeDemoState('BS12-086');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12TrueRockSpiritDemoState(scenario))}})

it('BS12-087 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','nine'],['card-negative','eight']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-087','localhost')).toEqual({kind:'bs12-087',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-087','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-087'):demos.createCardNegativeDemoState('BS12-087');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12UnderstandingDemoState(scenario))}})

it('BS12-088 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','response'],['card-negative','non-arena']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-088','localhost')).toEqual({kind:'bs12-088',cardNumber:'BS12-088',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-088','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-088'):demos.createCardNegativeDemoState('BS12-088');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12BlackSapphireDemoState('BS12-088',scenario))}})

it('BS12-088@1 generic routes match dedicated physical effect scenarios',()=>{for(const[prefix,scenario]of [['card','response'],['card-negative','non-arena']]as const){expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-088@1','localhost')).toEqual({kind:'bs12-088',cardNumber:'BS12-088@1',scenario});expect(demos.parseTestStateConfig('?test-state='+prefix+':BS12-088@1','example.com')).toBeNull();const state=prefix==='card'?demos.createCardCheckDemoState('BS12-088@1'):demos.createCardNegativeDemoState('BS12-088@1');assertBs12PhysicalFixture(state);expect(state).toEqual(demos.createBs12BlackSapphireDemoState('BS12-088@1',scenario))}})

it.each(['BS12-088','BS12-088@1']as const)('%s public normalentry deals printed3HP from exact physicaldeck',number=>{const before=demos.createBs12BlackSapphireDemoState(number,'deploy');assertBs12PhysicalFixture(before);const after=applyGameCommand(before,{kind:'deploy-cookie',playerId:'player-one',instanceId:'bs12-088-source'});assertBs12PhysicalFixture(after);expect(after.players['player-one'].battleArea[1].hpCards).toEqual(before.players['player-one'].deck.slice(0,3));expect(after.commandLog?.at(-1)?.commandKind).toBe('deploy-cookie')})
