/*
 * Generated by scripts/generate-card-pool.ts.
 * Do not edit manually; run the generator after promoting card data.
 */
import official_age_of_heroes_and_kingdoms_bs3_en_json_0 from '../../data/cards/official-age-of-heroes-and-kingdoms-bs3.en.json'
import official_brave_beginning_bs1_en_json_1 from '../../data/cards/official-brave-beginning-bs1.en.json'
import official_brave_beginning_bs2_en_json_2 from '../../data/cards/official-brave-beginning-bs2.en.json'
import official_sample_en_json_3 from '../../data/cards/official-sample.en.json'
import official_starter_deck_blue_en_json_4 from '../../data/cards/official-starter-deck-blue.en.json'
import official_starter_deck_green_en_json_5 from '../../data/cards/official-starter-deck-green.en.json'
import official_starter_deck_purple_en_json_6 from '../../data/cards/official-starter-deck-purple.en.json'
import official_starter_deck_yellow_en_json_7 from '../../data/cards/official-starter-deck-yellow.en.json'

export const officialCardDatasets = [
  official_age_of_heroes_and_kingdoms_bs3_en_json_0,
  official_brave_beginning_bs1_en_json_1,
  official_brave_beginning_bs2_en_json_2,
  official_sample_en_json_3,
  official_starter_deck_blue_en_json_4,
  official_starter_deck_green_en_json_5,
  official_starter_deck_purple_en_json_6,
  official_starter_deck_yellow_en_json_7,
] as const
