export { GameRuleError } from './errors'
export {
  executeCardEffect,
  getAttackDamageAgainst,
  getBreakToBattleCandidates,
  getBreakToHandBySumCandidates,
  getBreakToTrashCandidates,
  getEffectTargetCandidates,
  getEffectTargetCandidatesForEffect,
  getEffectSelectionCandidates,
  getEffectSelectionLimits,
  hasRequiredEffectTargets,
  getSupportEffectCandidates,
  getTrashCookieCandidates,
  getTrashToDeckCandidates,
  getTrashToHandCandidates,
  getTrashToSupportCandidates,
  getEffectiveAttack,
  isEffectConditionMet,
  isEffectTargeted,
  isEffectUntargeted,
  requiresEffectCardSelection,
  requiresTargetSelection,
  resolveOpponentHandDiscard,
  resolveInspectDeck,
  resolveDrawUpTo,
  selectEffectTargets,
  validateBreakToTrashTargets,
  expandChooseOne,
  expandChooseOneSequence,
} from './effects'
export {
  createBlueActivateSkillDemoState,
  createBlueInspectDeckDemoState,
  createBlueOptionalCostAttackDemoState,
  createDemoGame,
  createDemoSetupGame,
  createItemUsageDemoState,
  createStageUsageDemoState,
} from './demo'
export type { DeckConfig } from './demo'
export { createSeededRandom, createSeededShuffle } from './helpers'
export { getLegalTurnCommands } from './legal-actions'
export { createPlayerView } from './player-view'
export type {
  CookieInBattleView,
  PlayerSideView,
  PlayerView,
} from './player-view'
export { maskGameStateForViewer } from './masked-state'
export {
  getAttackEnergyCost,
  getAttackEnergyCostForState,
  getEnergyCostTotal,
  getRemainingEnergyCost,
  isEnergyColorCompatibleWithCost,
  selectEnergyPayment,
  validateEnergyPayment,
} from './energy'
export type { EnergyPaymentValidation } from './energy'
export {
  AI_PRESET_BS2_BEAN_DECK,
  AI_PRESET_BS2_BLUE_DECK,
  AI_PRESET_BS2_PURPLE_DECK,
  AI_PRESET_BS2_RED_DECK,
  AI_PRESET_BS2_YELLOW_DECK,
  AI_PRESET_BS3_BLUE_SORBET_DECK,
  AI_PRESET_BS3_GREEN_LILY_DECK,
  AI_PRESET_BS3_PURPLE_DARK_CACAO_DECK,
  AI_PRESET_BS3_RED_PITAYA_DECK,
  AI_PRESET_BS3_YELLOW_COUNTER_DECK,
  BS3_AI_PRESET_DECK_CHOICES,
  createAiPresetBs2BeanDeck,
  createAiPresetBs2BlueDeck,
  createAiPresetBs2PurpleDeck,
  createAiPresetBs2RedDeck,
  createAiPresetBs2YellowDeck,
  createAiPresetBs3BlueSorbetDeck,
  createAiPresetBs3GreenLilyDeck,
  createAiPresetBs3PurpleDarkCacaoDeck,
  createAiPresetBs3RedPitayaDeck,
  createAiPresetBs3YellowCounterDeck,
  createOfficialBlueStarterDeck,
  createOfficialGreenStarterDeck,
  createOfficialPurpleStarterDeck,
  createOfficialRedStarterDeck,
  createOfficialStarterDeck,
  createOfficialYellowStarterDeck,
  createCard,
  createDeckForChoice,
  DECK_CREATORS,
  OFFICIAL_BLUE_STARTER_DECK,
  OFFICIAL_DECK_RECIPES,
  OFFICIAL_GREEN_STARTER_DECK,
  OFFICIAL_PURPLE_STARTER_DECK,
  OFFICIAL_RED_STARTER_DECK,
  OFFICIAL_STARTER_DECK_RED,
  OFFICIAL_YELLOW_STARTER_DECK,
} from './starter-deck'
export type {
  AiPresetDeckChoice,
  Bs3AiPresetDeckChoice,
  BuiltInDeckChoice,
  DeckChoice,
  StarterDeckChoice,
  StarterDeckEntry,
} from './starter-deck'
export {
  getAllCardPoolEntries,
  getCardPoolEntry,
  getCardPoolEntriesByColor,
  getCardPoolEntriesByType,
  getCardPoolVariants,
  normalizeCardNumber,
} from './card-pool'
export type { CardPoolEntry } from './card-pool'
export {
  createCustomDeckId,
  createDeckFromCustomDeck,
  deleteCustomDeck,
  duplicateCustomDeck,
  loadCustomDecks,
  parseCustomDeckStorage,
  saveCustomDecks,
  validateCustomDeck,
  CUSTOM_DECK_STORAGE_VERSION,
  DECK_SIZE_MIN,
  DECK_SIZE_MAX,
  MAX_COPIES_PER_CARD,
} from './custom-deck'
export type { CustomDeck, CustomDeckEntry } from './custom-deck'
export { chooseRandomDeck } from './opening'
export {
  selectAiEnergyPayment,
  simulateAiMatch,
  takeAiStep,
} from './ai'
export {
  beginAttack,
  getAfterDamageEffectCandidates,
  getAfterDamageEffectMinMax,
  getFaintEffectCandidates,
  getFaintEffectMinMax,
  getBlockerCandidates,
  explainUnavailableTraps,
  getTrapCandidates,
  getTrapTargetCandidates,
  getTrapSelfTargetCandidates,
  isBlockDisabled,
  playBlocker,
  playTrap,
  resolveAttackEffect,
  resolveBattleAutomatically,
  resolveFaintEffect,
  resolveFlip,
  resolveNextAfterDamageEffect,
  resolveNextDamage,
  resolveOptionalCostAttack,
  skipTrap,
} from './battle'
export type { PlayBlockerOptions, PlayTrapOptions, ResolveFlipOptions } from './battle'
export {
  attackCookie,
  deployCookie,
  placeSupportCard,
  replaceDefeatedCookie,
  skipDefeatedCookieReplacement,
} from './actions'
export {
  activateStage,
  canActivateStage,
  canPlayItem,
  canPlayStage,
  getItemAbility,
  getStageAbility,
  playItem,
  playStage,
} from './card-abilities'
export { getRefreshCandidates, refreshDeck } from './refresh'
export { hasBlockingPending } from './pending'
export { getActingPlayerId, isPlayerControllingState } from './controller'
export {
  createGame,
  drawMulliganCompensation,
  forceMulliganOpeningHand,
  keepOpeningHand,
  mulliganOpeningHand,
  selectStartingCookie,
} from './setup'
export { advancePhase, canAttack, processEndPhaseEffects, TURN_PHASES } from './turn'
export {
  activateCookieSkill,
  canActivateCookieSkill,
  canPayEnergyCost,
  canPayTrashBattleCookieCost,
  canPayTrashToDeckCost,
  getTrashToDeckCostCandidates,
  getTrashBattleCookieCostCandidates,
  getTrashToDeckBottomCostCandidates,
  skipCookieOnPlay,
} from './skills'
export {
  evaluateBasicVictory,
  evaluateBreakLevelVictory,
  finishWithDefeat,
  finishWithVictory,
  getBasicDefeatReason,
  getBreakAreaLevel,
  isSpecialVictoryConditionMet,
  resolveBasicVictory,
  resolveBreakLevelVictory,
} from './victory'
export {
  continuePendingReplacements,
  finalizePendingReplacements,
  getCurrentReplacementTask,
  getReplacementCandidates,
  recordCookieDepartures,
} from './replacement'
export type {
  AttackModifier,
  AbilityCost,
  CardAbility,
  BaseCard,
  BreakLevelCondition,
  BreakToTrashEffect,
  CardEffect,
  CardColor,
  CardKeyword,
  CardSkill,
  CardType,
  CommandLogEntry,
  CookieCard,
  CookieInBattle,
  DamageEffect,
  DamageReceivedModifier,
  DeckToSupportEffect,
  DefeatReason,
  DrawEffect,
  DrawUpToEffect,
  EffectCondition,
  EffectContext,
  EffectDuration,
  EffectTargetSelector,
  EffectTargetSelectorSide,
  EffectTargetSide,
  EnergyColor,
  InspectDeckRestDestination,
  EnergyCost,
  BattleToBreakEffect,
  BreakToBattleEffect,
  BreakToHandBySumEffect,
  DisableAttackEffect,
  FieldToTrashAllEffect,
  FlipToSupportEffect,
  HpToSupportEffect,
  TrashCountAtLeastCondition,
  TrashToDeckEffect,
  TrashToHandEffect,
  FieldToTrashEffect,
  GameCard,
  GameEndReason,
  GameResult,
  GameState,
  GameStatus,
  FlipAbility,
  GainHpEffect,
  HpToTrashEffect,
  ModifyAttackEffect,
  ModifyDamageReceivedEffect,
  NonCookieCard,
  OpponentBattleToTrashEffect,
  OpponentDiscardHandEffect,
  OpponentRandomDiscardEffect,
  OpponentTrashCountAtLeastCondition,
  PendingFaintEffect,
  PendingOpponentHandDiscard,
  PlayerId,
  PlayerSetup,
  PlayerState,
  PendingBattle,
  PendingBattleStage,
  PendingEffectOrder,
  PendingEffectOrderItem,
  PendingEffectOrderKind,
  PendingReplacement,
  PreventKnockoutEffect,
  ReplacementTask,
  ReturnToHandEffect,
  ReturnToDeckBottomEffect,
  SetActiveEffect,
  Shuffle,
  SkillTrigger,
  SupportCard,
  StageAbility,
  StageCard,
  SpecialVictoryCondition,
  SupportToTrashEffect,
  TargetedCardEffect,
  TrapAbility,
  TrapCondition,
  TrashToSupportEffect,
  TurnPhase,
  VictoryReason,
} from './types'
export {
  appendCommandLogEntry,
  applyGameCommand,
  getPendingDecision,
} from './commands'
export type {
  ApplyGameCommandOptions,
  FaintEffectDecision,
  GameCommand,
  InspectDeckDecision,
  OpponentHandDiscardDecision,
  OptionalCostAttackDecision,
  DrawUpToDecision,
  EffectOrderDecision,
  StageTriggerDecision,
  PendingDecision,
  PendingDecisionCommand,
  PlayerActionCommand,
  ResolveEffectOrderCommand,
  ResolveFaintEffectCommand,
  ResolveInspectDeckCommand,
  ResolveOpponentHandDiscardCommand,
  ResolveOptionalCostAttackCommand,
  ResolveDrawUpToCommand,
  ResolveStageTriggerCommand,
  AdvancePhaseCommand,
  ActivateSkillCommand,
  ActivateStageCommand,
  AttackCommand,
  DeployCookieCommand,
  DrawMulliganCompensationCommand,
  ForceMulliganOpeningHandCommand,
  KeepOpeningHandCommand,
  MulliganOpeningHandCommand,
  PlaceSupportCommand,
  PlayBlockerCommand,
  PlayItemCommand,
  PlayStageCommand,
  PlayTrapCommand,
  RefreshDeckCommand,
  ReplaceCookieCommand,
  ResolveAttackEffectCommand,
  ResolveBattleCommand,
  ResolveFlipCommand,
  ResolveNextDamageCommand,
  SelectStartingCookieCommand,
  SkipOnPlayCommand,
  SkipReplacementCommand,
  SkipTrapCommand,
} from './commands'
export {
  commandFromLogEntry,
  replayCommandLog,
  replayCommands,
} from './replay'
export {
  buildReplayIssueBundle,
  parseReplayIssueBundle,
  ReplayIssueBundleParseError,
  serializeReplayIssueBundle,
} from './replay-issue-bundle'
export type {
  BuildReplayIssueBundleOptions,
  ReplayIssueBundleV1,
} from './replay-issue-bundle'
export type {
  AiActionType,
  AiDecision,
  AiDecisionReason,
  AiEffectSelection,
  AiLevel,
  AiMatchMetrics,
  AiMatchResult,
  AiStepOptions,
  SimulateAiMatchOptions,
} from './ai'
export type {
  AiDetailedResult,
  ReplacementEvent,
  AttackEvent,
  TurnProgression,
  EndInfo,
  BehaviorMetrics,
} from './ai/types'
export { evaluatePlayerView } from './ai/evaluated-turn-handler'
export { simulateAiMatchDetailed } from './ai-detailed-sim'
