import type { PlayerView } from '../../player-view'
import type { PlayerId } from '../../types'
import type { ActionIdentity } from './action-score'
import rawDefaultExperienceProfile from '../../../../data/ai/bs9-lv5-experience.json'

/**
 * A compact, public-information-only decision trace for one AI player.
 *
 * The trace deliberately stores counts rather than cards drawn from hidden
 * zones.  It is therefore safe to aggregate across matches and use as a
 * bounded prior for later Lv.5 decisions.
 */
export interface AiDecisionProfile {
  totalDecisions: number
  byAction: Record<string, number>
  byCardAction: Record<string, Record<string, number>>
}

export interface TournamentExperienceSource {
  tournamentId: string
  rosterSize: number
  rounds: number
  swissMatches: number
  seed: number
  generatedAt: string
}

export interface AiTournamentExperienceProfile {
  schemaVersion: 1
  id: string
  strategyVersion: string
  scope: {
    series: string
  }
  source: TournamentExperienceSource
  actionWeights: Record<string, number>
  cardActionWeights: Record<string, Record<string, number>>
  sampleCounts: {
    actions: Record<string, number>
    cardActions: Record<string, Record<string, number>>
  }
}

export interface TournamentExperienceAdjustment {
  amount: number
  detail: string
}

interface ExperienceCell {
  matches: number
  observations: number
  exposure: number
  outcome: number
}

export interface AiTournamentExperienceAccumulator {
  matches: number
  decisiveMatches: number
  byAction: Map<string, ExperienceCell>
  byCardAction: Map<string, Map<string, ExperienceCell>>
}

/** Runtime prior generated by the BS9 1024-player training command. */
export const DEFAULT_LV5_TOURNAMENT_EXPERIENCE_PROFILE =
  rawDefaultExperienceProfile as AiTournamentExperienceProfile

const ZERO_ADJUSTMENT: TournamentExperienceAdjustment = {
  amount: 0,
  detail: '沒有適用的 BS9 賽事經驗修正。',
}

const clamp = (value: number, min: number, max: number): number =>
  Math.min(max, Math.max(min, value))

const visibleSelfCards = (view: PlayerView) => [
  ...view.hand,
  // EXTRA Deck is private from the opponent but fully visible to its owner;
  // retaining it here lets BS9 EXTRA decisions receive their card-specific
  // tournament signal without exposing hidden opponent information.
  ...(view.extraDeck ?? []),
  ...view.self.battleArea.map((cookie) => cookie.card),
  ...view.self.supportArea.map((support) => support.card),
  ...view.self.breakArea,
  ...view.self.discardPile,
  ...(view.self.stage ? [view.self.stage.card] : []),
]

const sourceCardFor = (
  view: PlayerView,
  sourceInstanceId: string | undefined,
) => sourceInstanceId === undefined
  ? undefined
  : visibleSelfCards(view).find((card) => card.instanceId === sourceInstanceId)

/**
 * Score one candidate using the learned tournament prior.  The prior is
 * intentionally small and only applies to the configured series, so it can
 * refine the existing public-view evaluator without replacing rules,
 * terminal outcomes, or card-capability reasoning.
 */
export const scoreTournamentExperience = (
  profile: AiTournamentExperienceProfile | null | undefined,
  view: PlayerView,
  identity: ActionIdentity,
): TournamentExperienceAdjustment => {
  if (!profile) return ZERO_ADJUSTMENT
  const sourceCard = sourceCardFor(view, identity.sourceInstanceId)
  const seriesPrefix = `${profile.scope.series.toUpperCase()}-`
  if (!sourceCard?.id.toUpperCase().startsWith(seriesPrefix)) {
    return ZERO_ADJUSTMENT
  }

  const cardWeight = profile.cardActionWeights[sourceCard.id]?.[identity.kind]
  const actionWeight = profile.actionWeights[identity.kind]
  if (cardWeight === undefined && actionWeight === undefined) {
    return ZERO_ADJUSTMENT
  }

  // Card/action observations are more specific.  A small generic component
  // keeps sparse actions useful without letting a single action dominate.
  const raw = (cardWeight ?? 0) +
    (cardWeight === undefined ? actionWeight ?? 0 : Math.round((actionWeight ?? 0) / 4))
  const amount = clamp(Math.round(raw), -24, 24)
  if (amount === 0) return ZERO_ADJUSTMENT
  const sampleCount = cardWeight !== undefined
    ? profile.sampleCounts.cardActions[sourceCard.id]?.[identity.kind] ?? 0
    : profile.sampleCounts.actions[identity.kind] ?? 0
  return {
    amount,
    detail: `BS9 瑞士賽事經驗：${sourceCard.id}／${identity.kind}，${amount > 0 ? '+' : ''}${amount}（${sampleCount} 筆公開樣本）。`,
  }
}

export const createAiTournamentExperienceAccumulator = (): AiTournamentExperienceAccumulator => ({
  matches: 0,
  decisiveMatches: 0,
  byAction: new Map(),
  byCardAction: new Map(),
})

const createCell = (): ExperienceCell => ({
  matches: 0,
  observations: 0,
  exposure: 0,
  outcome: 0,
})

const recordCell = (
  cell: ExperienceCell,
  observations: number,
  playerOutcome: 1 | -1,
  totalDecisions: number,
): void => {
  if (observations <= 0) return
  cell.matches += 1
  cell.observations += observations
  const exposure = observations / Math.max(1, totalDecisions)
  cell.exposure += exposure
  cell.outcome += exposure * playerOutcome
}

const recordActionCounts = (
  map: Map<string, ExperienceCell>,
  counts: Record<string, number>,
  playerOutcome: 1 | -1,
  totalDecisions: number,
): void => {
  for (const [action, observations] of Object.entries(counts)) {
    const cell = map.get(action) ?? createCell()
    recordCell(cell, observations, playerOutcome, totalDecisions)
    map.set(action, cell)
  }
}

const recordCardActionCounts = (
  map: Map<string, Map<string, ExperienceCell>>,
  counts: Record<string, Record<string, number>>,
  playerOutcome: 1 | -1,
  totalDecisions: number,
): void => {
  for (const [cardId, actions] of Object.entries(counts)) {
    const cardMap = map.get(cardId) ?? new Map<string, ExperienceCell>()
    recordActionCounts(cardMap, actions, playerOutcome, totalDecisions)
    map.set(cardId, cardMap)
  }
}

export const recordAiTournamentMatchExperience = (
  accumulator: AiTournamentExperienceAccumulator,
  profiles: Partial<Record<PlayerId, AiDecisionProfile>>,
  winner: PlayerId | null,
): void => {
  if (!winner) return
  accumulator.matches += 1
  accumulator.decisiveMatches += 1
  for (const playerId of ['player-one', 'player-two'] as const) {
    const profile = profiles[playerId]
    if (!profile || profile.totalDecisions <= 0) continue
    const outcome: 1 | -1 = winner === playerId ? 1 : -1
    recordActionCounts(
      accumulator.byAction,
      profile.byAction,
      outcome,
      profile.totalDecisions,
    )
    recordCardActionCounts(
      accumulator.byCardAction,
      profile.byCardAction,
      outcome,
      profile.totalDecisions,
    )
  }
}

const sortedRecord = <T>(map: Map<string, T>): Record<string, T> =>
  Object.fromEntries([...map.entries()].sort(([left], [right]) => left.localeCompare(right)))

const finalizeCellWeight = (cell: ExperienceCell): number => {
  if (cell.matches < 3 || cell.exposure <= 0) return 0
  const signal = cell.outcome / cell.exposure
  const confidence = Math.min(1, Math.sqrt(cell.matches / 12))
  return clamp(Math.round(signal * 24 * confidence), -24, 24)
}

const finalizeActionWeights = (
  map: Map<string, ExperienceCell>,
): { weights: Record<string, number>; samples: Record<string, number> } => {
  const weights = new Map<string, number>()
  const samples = new Map<string, number>()
  for (const [key, cell] of map.entries()) {
    const weight = finalizeCellWeight(cell)
    if (weight !== 0) weights.set(key, weight)
    samples.set(key, cell.observations)
  }
  return { weights: sortedRecord(weights), samples: sortedRecord(samples) }
}

export const finalizeAiTournamentExperience = (
  accumulator: AiTournamentExperienceAccumulator,
  metadata: {
    id: string
    strategyVersion: string
    series: string
    source: TournamentExperienceSource
  },
): AiTournamentExperienceProfile => {
  const action = finalizeActionWeights(accumulator.byAction)
  const cardWeights = new Map<string, Record<string, number>>()
  const cardSamples = new Map<string, Record<string, number>>()
  for (const [cardId, actionMap] of accumulator.byCardAction.entries()) {
    const finalized = finalizeActionWeights(actionMap)
    if (Object.keys(finalized.weights).length > 0) {
      cardWeights.set(cardId, finalized.weights)
    }
    if (Object.keys(finalized.samples).length > 0) {
      cardSamples.set(cardId, finalized.samples)
    }
  }

  return {
    schemaVersion: 1,
    id: metadata.id,
    strategyVersion: metadata.strategyVersion,
    scope: { series: metadata.series },
    source: metadata.source,
    actionWeights: action.weights,
    cardActionWeights: sortedRecord(cardWeights),
    sampleCounts: {
      actions: action.samples,
      cardActions: sortedRecord(cardSamples),
    },
  }
}
