import { readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const projectRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
export const cardsDirectory = join(projectRoot, 'data', 'cards')
export const generatedPoolPath = join(
  projectRoot,
  'src',
  'game',
  'generated-card-pool.ts',
)

export const getCardDataFiles = (directory = cardsDirectory): string[] =>
  readdirSync(directory)
    .filter((file) => file.endsWith('.json'))
    .sort((left, right) => left.localeCompare(right))

const toImportIdentifier = (file: string, index: number): string => {
  const identifier = file
    .replace(/[^A-Za-z0-9_$]/g, '_')
    .replace(/^[^A-Za-z_$]/, '_$&')
  return `${identifier}_${index}`
}

export const createGeneratedPoolSource = (files: readonly string[]): string => {
  const imports = files.map((file, index) => {
    const identifier = toImportIdentifier(file, index)
    return `import ${identifier} from '../../data/cards/${file}'`
  })
  const identifiers = files.map((file, index) => toImportIdentifier(file, index))

  return [
    '/*',
    ' * Generated by scripts/generate-card-pool.ts.',
    ' * Do not edit manually; run the generator after promoting card data.',
    ' */',
    ...imports,
    '',
    'export const officialCardDatasets = [',
    ...identifiers.map((identifier) => `  ${identifier},`),
    '] as const',
    '',
  ].join('\n')
}

export const generateCardPool = (
  directory = cardsDirectory,
  outputPath = generatedPoolPath,
): string[] => {
  const files = getCardDataFiles(directory)
  if (files.length === 0) {
    throw new Error('data/cards/ 必須至少包含一份卡牌資料。')
  }
  writeFileSync(outputPath, createGeneratedPoolSource(files), 'utf8')
  return files
}

const isDirectExecution =
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href

if (isDirectExecution) {
  const files = generateCardPool()
  console.log(`已生成卡池 registry：${files.length} 個資料檔案。`)
}
